version: '3.8'

services:
  # Application Spring Boot (H2 embarqu√©e, pas besoin de MySQL)
  ecredit-backend:
    image: umaimaba/ecredit-backend:${IMAGE_TAG:-latest}
    container_name: ecredit-backend-app
    ports:
      - "8085:8080"
    environment:
      # Variables pour Spring Boot
      SPRING_PROFILES_ACTIVE: default
      SERVER_PORT: 8080
    networks:
      - ecredit-network
    restart: unless-stopped
    
networks:
  ecredit-network:
    driver: bridge
