version: '3.8'

services:
  # Application Spring Boot
  ecredit-backend:
    image: umaimaba/ecredit-backend:${IMAGE_TAG:-latest}
    container_name: ecredit-backend-app
    ports:
      - "8085:8080"        # Port exposé pour le backend
    environment:
      SPRING_PROFILES_ACTIVE: default
      SERVER_PORT: 8080
    networks:
      - ecredit-network
    restart: unless-stopped

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"        # Port pour accéder à Prometheus
    networks:
      - ecredit-network
    restart: unless-stopped

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"        # Port pour accéder à Grafana
    networks:
      - ecredit-network
    depends_on:
      - prometheus
    restart: unless-stopped

networks:
  ecredit-network:
    driver: bridge
