version: "3.8"

services:
  # ============================================
  # APPLICATION SPRING BOOT (avec H2 embarqu√©e)
  # ============================================

  ecredit-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: umaimaba/ecredit-backend:latest
    ports:
      - "8085:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SERVER_PORT=8080
    networks:
      - ecredit-network
    restart: unless-stopped

networks:
  ecredit-network:
    driver: bridge
