global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ecredit-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ecredit-backend-app:8080']
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ecredit-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ecredit-backend-app:8080']
